[package]
name = "ccp_copa"
version = "0.1.0"
authors = ["Venkat Arun <venkatar@mit.edu>"]

[dependencies]
clap="2.29"
slog = "2"
slog-term = "2"
slog-async = "2"
time="0.1"
portus = { git = "https://github.com/ccp-project/portus" }
